######################## default configuration ####################
baseURL = "https://kmilo_collado.gitlab.io/portafolio/"
title = "Kmilo Collado"
defaultContentLanguage = "es"
languageCode = "es"
theme = "somrat"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "10"


# disable language
disableLanguages = [] # disable language from here
# google analutics
googleAnalytics = "" # example : UA-123-45
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com



############################# Outputs ##############################
[outputs]
home = ["HTML"]

[markup.goldmark.renderer]
unsafe= true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
[[params.plugins.css]]
link = "plugins/hover/hover.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.carousel.min.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.theme.default.min.css"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.css]]
link = "/assets/css/style.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/wow.min.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/jquery.waypoints.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/owl-carousel/owl.carousel.min.js"


#################### default parameters ################################
[params]
favicon = "images/favicon.png"
logo_light = "images/logo-light.png"
logo_dark = "images/logo-dark.png"
logo_width = "150px"
css = ["css/style.css"]
# Meta data
description = "Mi portafolio Kmilo Collado"
author = "kmilo"
whatsapp_num = "+5352391362"
cv = "docs/CV.pdf"

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.
  
############################# social site ########################
[[params.social]]
icon = "fab fa-facebook-f"
link = "https://www.facebook.com/kmilocollado"

[[params.social]]
icon = "fab fa-twitter"
link = "https://twitter.com/Kmilo_Collado"

[[params.social]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/kmilocollado"

[[params.social]]
icon = "fab fa-whatsapp"
link = "https://wa.me/+5352391362"

[[params.social]]
icon = "fab fa-telegram"
link = "https://t.me/kmilo_collado"

################################### Español language #####################################
[Languages.es]
languageName = "Es"
languageCode = "es-esp"
contentDir = "content/español"
weight = 2
home = "Inicio"
# copyright
copyright = "Copyright &copy; 2020 Kmilo Collado"


################# español navigation ##################

# main menu
[[Languages.es.menu.main]]
name = "Inicio"
url = "/"
weight = 1

[[Languages.es.menu.main]]
name = "Acerca de"
pre = "#"
url = "acerca-de"
weight = 2

[[Languages.es.menu.main]]
name = "Servicios"
pre = "#"
url = "service"
weight = 3

[[Languages.es.menu.main]]
name = "Portafolio"
pre = "#"
url = "portfolio"
weight = 4


[[Languages.es.menu.main]]
name = "Contacto"
pre = "#"
url = "contact"
weight = 5


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2020 Kmilo Collado"


################# english navigation ##################

# main menu
[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.en.menu.main]]
name = "About me"
pre = "#"
url = "about"
weight = 2

[[Languages.en.menu.main]]
name = "Service"
pre = "#"
url = "service"
weight = 3

[[Languages.en.menu.main]]
name = "Portfolio"
pre = "#"
url = "portfolio"
weight = 4

[[Languages.en.menu.main]]
name = "Contact"
pre = "#"
url = "contact"
weight = 5



